apiVersion: apps/v1
kind: Deployment
metadata:
  name: sveltos-applier-manager
  namespace: projectsveltos
  labels:
  {{- include "ciroos.labels" . | nindent 4 }}
   {{- with .Values.sveltosApplierManager.labels }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
   {{- with .Values.sveltosApplierManager.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sveltos-applier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sveltos-applier
        {{- with .Values.sveltosApplierManager.labels }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      annotations:
        kubectl.kubernetes.io/default-container: controller
        {{- with .Values.sveltosApplierManager.annotations }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      {{- with .Values.sveltosApplierManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sveltosApplierManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args:
        - --diagnostics-address=:8443
        - --cluster-namespace={{ .Values.clusterNamespace }}
        - --cluster-name={{ .Values.clusterName }}
        - --cluster-type=Sveltos
        - --secret-with-kubeconfig=pullmode-secret
        - --v=5
        - --version=pull-mode
        command:
        - /manager
        env:
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.cpu
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.sveltosApplierManager.controller.image.repository }}:{{ .Values.sveltosApplierManager.controller.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
        name: controller
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.sveltosApplierManager.controller.resources | nindent
          10 }}
        securityContext: {{- toYaml .Values.sveltosApplierManager.controller.containerSecurityContext
          | nindent 10 }}
      securityContext: {{- toYaml .Values.sveltosApplierManager.podSecurityContext | nindent
        8 }}
      serviceAccountName: sveltos-applier-manager
      terminationGracePeriodSeconds: 10