apiVersion: v1
kind: Secret
metadata:
  name: pullmode-secret
  namespace: projectsveltos
  labels:
  {{- include "ciroos.labels" . | nindent 4 }}
data:
  policy0: {{ .Values.pullmodeSecret.kubeconfig }}
type: Opaque