apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sveltos-applier-manager-crd-permission
  labels:
  {{- include "ciroos.labels" . | nindent 4 }}
rules:
- apiGroups:
  - lib.projectsveltos.io
  - config.projectsveltos.io
  - lib.ciroos.ai
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'