apiVersion: v1
kind: Service
metadata:
  name: sveltos-applier-metrics-service
  namespace: projectsveltos
  labels:
  {{- include "ciroos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sveltosApplierMetricsService.type }}
  selector:
    app.kubernetes.io/name: sveltos-applier
  ports:
  {{- .Values.sveltosApplierMetricsService.ports | toYaml | nindent 2 }}