apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "installer.fullname" . }}-bootstrap
  labels:
  {{- include "installer.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.bootstrap.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ciroos-uninstaller
  namespace: default
  labels:
  {{- include "installer.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "1"