apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "installer.fullname" . }}-bootstrap
  labels:
  {{- include "installer.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.bootstrap.serviceAccount.annotations | nindent 4 }}