apiVersion: batch/v1
kind: Job
metadata:
  name: ciroos-uninstall
  namespace: default
  labels:
  {{- include "installer.labels" . | nindent 4 }}
   {{- with .Values.uninstaller.labels }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "5"
   {{- with .Values.uninstaller.annotations }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  ttlSecondsAfterFinished: 240
  template:
    metadata:
      {{- with .Values.uninstaller.labels }}
      labels:
          {{- range $key, $value := . }}
          {{ $key }}: {{ $value | quote }}
          {{- end }}
      {{- end }}
      {{- with .Values.uninstaller.annotations }}
      annotations:
          {{- range $key, $value := . }}
          {{ $key }}: {{ $value | quote }}
          {{- end }}
     {{- end }}
    spec:
      {{- with .Values.uninstaller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.uninstaller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args: {{- toYaml .Values.uninstaller.uninstall.args
          | nindent 8 }}
        name: uninstall
        image: {{ .Values.uninstaller.uninstall.image.repository }}:{{ .Values.uninstaller.uninstall.image.tag }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      serviceAccountName: ciroos-uninstaller
      restartPolicy: OnFailure
  backoffLimit: 4